"""GET /model — real evaluation + benchmark metrics generated by the
ml/train_model.py and ml/compare_models.py scripts. No hardcoded numbers."""

import json
from pathlib import Path

from fastapi import APIRouter

router = APIRouter(tags=["model"])

ML_DIR = Path(__file__).resolve().parent.parent.parent / "ml"


def _read_json(name: str) -> dict | None:
    path = ML_DIR / name
    if not path.exists():
        return None
    with open(path) as f:
        return json.load(f)


@router.get("/model")
def get_model_info():
    return {
        "evaluation": _read_json("evaluation.json"),
        "comparison": _read_json("model_comparison.json"),
    }
